return "return {[\"background\"] = \"gui_rohanbg.png\", " ..
	"[\"title\"] = \"Concerning the Rings of Power\"," ..
	"[\"page_max\"] = 14, [\"text_len\"] = 8800, [\"owner\"] = \"An Elven Smith\"," ..
	"[\"text\"] = \"When certain materials are bound together, and united into a single, cohesive new material, certain changes take place, not only in their physical structure but also in their capabilities and uses.\\\n\\\n" ..
	"Having spent many years working on these concepts, with the help and guidance of Annatar, the kindly lord of gifts, we have come to a great understanding of these matters. From this knowledge we have been able to devise objects of great power, unknown to our land until this time, objects which have been seen only among the Valar. Our knowledge concerns gold, silver, and gems, fashioned into the form of rings. So that this knowledge might be passed on, I have determined that it is necessary to write about the process through which these objects are made.\\\n\\\n" ..
	"RINGSILVER\\\n\\\n" ..
	"The first steps involve the preparation of ringsilver, out of which the ring is formed. First, normal ingots of gold and silver, which even the dwarves consider to be pure, must be taken, and purified further. This is done by heating a gold or silver ingot in a normal furnace, and leaving it there for a longer time. After this, the two pure ingots must be heated up, and combined into goldsilver in a dual furnace like that used for bronze.\\\n\\\n" ..
	"After several goldsilver ingots have been made they can be smelted together in a special furnace, made by surrounding a normal furnace in obsidian. In this special furnace you must combine the goldsilver with mithril, rough rock, and fuel. When the ringsilver has been smelted, it will appear on top of the furnace, propelled out by force of the reaction. The ringsilver will be very hot, and must be cooled down in water within ten seconds, in order for it to form the correct structure. Then you have ringsilver, the basis of the ring!\\\n\\\n" ..
	"RINGS\\\n\\\n" ..
	"Out of the ringsilver, you can then form a ring. This is not easy,	despite sounding so. The ring formed must be perfect in shape, and therefore cannot be formed in one step. First, two ingots of ringsilver must be taken, and placed together in the dual furnace. Then, the ingots will fuse together, forming a quarter of a ring. When two of these have been obtained, they must be smelted together in order to obtain a half ring. When two half rings have been formed, they must be smelted again to produce a whole ring.\\\n\\\n" ..
	"After the ring has been made, it must be prepared in order that a gem might be set in it. First, two pins must be crafted out of one ingot of ringsilver. Then the pins must be added to the ring, one above and to the left, the other above and to the right.\\\n" ..
	"After this has been done, the ring is ready to be combined with a gem.\\\n\\\n" ..
	"GEMS\\\n\\\n" ..
	"In the depths of the earth, certain gems of various colours can be found. These gems require processing before they can be added to the ring. Even the first step of mining these gems out is not easy. Normal pickaxes cannot dig them, because the stone in which they are encased is so hard. Three rough rock should be placed above a mithril pickaxe, one directly above, one to the left, one to the right. Even with this pickaxe, it is still rare to obtain a gem from the ore.\\\n\\\n" ..
	"When you have mined several gems, you can begin the next stages of preparing the gem. The gem which you receive from the ore will be encrusted in stone, which needs to be removed. This can be done by smelting the gem in a normal furnace which will return an uncut gem. This new gem must be cut with a chisel in order to shape it for the ring.\\\n\\\n" ..
	"To make the chisel, a stick must be placed in the bottom left corner of the grid, and then an ingot of steel must be placed in the middle. To the right and above that, an ingot of mithril must be placed, and this will form a chisel. This should then be crafted with an uncut gem, and if your hand is steady the gem will be successfully cut.\\\n\\\n" ..
	"But even then the process is not complete, and there remains one final step. The gem must be polished, and this can be done by surrounding it with sand. If everything is successful, then you will have a gem which is ready to be combined with the ring.\\\n\\\n" ..
	"RINGS OF POWER\\\n\\\n" ..
	"Now, you should have a ring and a gem prepared and ready to be combined. First, the polished gem must be combined with the prepared ring in the dual furnace. The ring and the gem will flawlessly fuse together, creating a united whole, which cannot be separated.\\\n\\\n" ..
	"After the gem has been fused to the ring, there are two steps to finish the ring. First, the ring must be polished by surrounding it with rough rock. This must then be smelted in a very special furnace, along with certain other materials. The special furnace is made in the following way:\\\n\\\n" ..
	"A ringsliver furnace is placed in the middle. Below, to the right and left of this are placed blocks of tilkal. Directly above and below the ringsilver furnace are placed blocks of mithril. Above, to the right and left of it, are placed galvorn blocks, and finally, to each side of it are placed blocks of steel. This complex structure is necessary not only to both absorb and retain heat, but also the materials themselves contribute to the changing of the properties of the ring.\\\n\\\n" ..
	"When this furnace has been built, it cannot simply be placed down. Under it, you must place a three by three square of lava, and the furnace must rest in the middle of this, directly above the lava. When the furnace has been placed, in it must be put the polished ring, one block of mithril, one block of tilkal, one block of galvorn, and any kind of fuel. It will take a few minutes for the materials to mix and the ring to be imbued with power.\\\n\\\n" ..
	"When the time has passed, stand well back from the furnace. If the ring has been successfully made, there will be an explosion, which will leave a large crater. At the bottom you will find a ring of power!\\\n\\\n" ..
	"CONCLUSION\\\n\\\n" ..
	"The rings are wondrous things, and the process of making them is complex. Should you acquire one, we beg you to use these objects of power to serve others and fight evil, lest their power be turned against us by the Enemy. For in nothing is the power of the Dark Lord more clearly shown than in the estrangement that divides all those who still oppose him!\\\n\\\n" ..
	"Farewell and blessings to you, unknown reader!\\\n\\\n\\\n" ..
    "THE FOUR RINGS\\\n\\\n" ..
    "Vilya (blue gem): When activated, this amazing ring grants flight, speed, and higher jump - for a limited time (Press K to enable flight)\\\n\\\n" ..
    "Narya (red gem): Worn around the neck (chest slot), this ring grants total protection similar to an entire compliment of mithril or galvorn armor. Only when worn with Nenya is 100 armor possible.\\\n\\\n" ..
    "Nenya (white gem): Worn on the hand (shield slot), this ring will heal and sustain you. It also defends as a shield.\\\n" ..
    "Both Nenya and Narya grant increased mana and toughness (life total).\\\n\\\n" ..
    "Dwarvish Ring (purple gem): Held in the hand, this dwarvish ring is an unbreakable pick, axe, shovel, and sword! Also, combine this ring with ore lumps to get twice the amount of *smelted* ore.\\\n\"}"
