return "return {[\"background\"] = \"gui_elfbg.png\", " ..
	"[\"title\"] = \"Legendary Weapons & Artifacts\"," ..
	"[\"page_max\"] = 7, [\"text_len\"] = 2000, [\"owner\"] = \"a Dwarvish Smith\"," ..
	"[\"text\"] = \"Descriptions of the most powerful weapons in Middle-earth are contained within these pages. Recipes may be found in the Forbidden Book.\\\n\\\n" ..
	"GLAMDRING: Known as the Foe-Hammer (or Beater to the orcs), this powerful sword fires blue bolts of magic energy. These bolts travel slowly, so the sword is best used at close range.\\\n\\\n" ..
	"ELVISH GLAIVE: This rare elvish weapon has the reach of a spear and the power of an elvish longsword - but that's not all!  Should you take damage while fighting enemies, there is a good chance the glaive will restore some health on each hit.\\\n\\\n" ..
	"GIMLI'S AXE: Wielded with deft strokes by the dwarven folk, this axe does decent damage.  However, its great power lies in the ability to make a 'vorpal' hit 5% of the time, which will completely destroy monsters by cleaving them in two!  Players instead take a huge amount of damage.\\\n\\\n" ..
	"\\\"Speak, or I will put a dint in your hat that even a wizard will find hard to deal with!\\\"\\\n\\\n" ..
	"STING: Thus named by Bilbo Baggins after his battle in Mirkwood, this wondrous short sword grants the ability to teleport over a medium distance, while cutting down enemies in its path. In addition, the sword will glow when orcs, wargs,  trolls, or evil monsters are near.  A secondary function (sneak + click) makes you very sneaky by transforming you into a mouse for one hour!  You can also toggle the transformation off by using the secondary function again.  Beware, teleporting can be dangerous!\\\n\\\n" ..
	"WIZARD STAFF: This magic staff allows you to project beams of light at your foes. While similar to Glamdring, the beams of light are more powerful in every respect.  The staff can also create a ring of fire around the caster (sneak + click).  Fire damages monsters not immune to fire, and does 4 damage per second to players (except those who have special items such as Dwarven armor).\\\n\\\n" ..
	"\\\"I was hard put to it indeed: such light and flame cannot have been seen on Weathertop since the war-beacons of old.\\\"\\\n\\\n" ..
	"GROND: Mighty hammer of the underworld, once wielded by Morgoth. This weapon shakes the ground and causes tremendous damage. Be careful, as Grond shows no discretion, and can easily kill its owner!  The secondary function lets you take the form of a Nazgul, which monsters of all kinds will ignore (but also slows you down).  Attacking a monster or sneak+clicking again will remove the form.\\\n\\\n" ..
	"STAFF OF SARUMAN: Like Saruman himself, this staff can shoot balls of powerful wizard-fire and teleport the wielder short distances. The staff was broken in two, but can be mended... The two halves must be surrounded by mithril blocks and then fused together in a dual furnace. Incredibly expensive to make, but also incredibly powerful!\\\n\\\n" ..
	"ELFSTONE: Ties your body to the land.  Sneak+click to set a home location, and then use the normal way to teleport back! Takes a large amount of mana to use.\\\n\\\n" ..
	"PHIAL OF GALADRIEL: A light when all other lights go out. As a source of light, this needs only to be in your inventory to illuminate even the darkest cave!\\\n\\\n" ..
	"HIGH ELVISH BOW: This elvish bow requires no ammunition. As the string is pulled back, an arrow of blue fire appears, which travels at a great speed. The arrow then bursts into blue flame. Also, when the bow is in your inventory it imbues you with powerful sight (press Z to zoom in).\\\n\"}"
