mobs:register_mob("dmobs:wyvern", {
   type = "monster",
   passive = false,
   attacks_monsters = false,
   damage = 10,
   reach = 6,
   attack_type = "dogshoot",
   dogshoot_stop = false,
   shoot_interval = 1.5,
	dogshoot_switch = 2,
	dogshoot_count = 0,
	dogshoot_count_max = 8,
   arrow = "dmobs:poison",
   shoot_offset = 0.7,
   hp_min = 100,
   hp_max = 150,
   armor = 100,
	collisionbox = {-0.6, -1.4, -0.6, 0.6, 0.6, 0.6},
   visual = "mesh",
   mesh = "wyvern.b3d",
   textures = {
      {"dmobs_wyvern.png"},
   },
   blood_texture = "mobs_blood.png",
   visual_size = {x=.8, y=.8},
   makes_footstep_sound = true,
	runaway = true,
	jump_chance = 30,
	walk_chance = 80,
	pathfinding = true,
   walk_velocity = 3,
   _acceleration = 0.2,
   run_velocity = 5,
   fly_velocity = 6,
   fall_speed = -2,
   jump = true,
   fly = true,
   drops = {
      {name = "dmobs:dragon_egg_poison", chance = 100, min = 1, max = 1},
	  {name = "dmobs:dragon_egg_lightning", chance = 100, min = 1, max = 1},
	  {name = "dmobs:dragon_egg_fire", chance = 100, min = 1, max = 1},
	  {name = "dmobs:dragon_egg_ice", chance = 100, min = 1, max = 1},
   },
   sounds = {
	  shoot_attack = "mobs_fireball",
	  random = "velociraptor",
   },
   water_damage = 0,
   lava_damage = 2,
   light_damage = 0,
   view_range = 80,
   animation = {
      speed_normal = 20,
      speed_run = 30,
      walk_start = 33,
      walk_end = 68,
      stand_start = 1,
      stand_end = 30,
      run_start = 33,
      run_end = 68,
      punch_start = 70,
      punch_end = 89,
   },
	knock_back = 2,
})


--mobs:register_egg("dmobs:wyvern", "Boss Wyvern", "dmobs_egg3.png", 1)
